### ISSUE TITLE
Upgrade to maragu.dev/gomponents

### ISSUE THREAD

**Issue by markuswustenberg** [eduardolat/gomponents-lucide#1]
Hey @eduardolat! 😊

I'm in the process of moving gomponents to the maragu.dev/gomponents namespace. Could you try upgrading your library to that with `go get maragu.dev/gomponents@v1.0.0-beta1` and see if you hit any issues?

After that, it should simply be a global search/replace in the project: `github.com/maragudk/gomponents` -> `maragu.dev/gomponents`, followed by `go mod tidy`.

I hope you have the time for this, and thank you!

**Comment by eduardolat** [comment]
Hi @markuswustenberg congratulations for reaching v1!!!!!!

Here is the latest release including gomponents v1, have a good day! https://github.com/eduardolat/gomponents-lucide/releases/tag/v1.4.0

**Comment by markuswustenberg** [comment]
@eduardolat excellent! And thank you. 😊
